name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue here.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: Device
    attributes:
      label: Which type of Device are you seeing the problem on?
      multiple: true
      options:
        - Phone
        - Emulator
        - Tablets
    validations:
      required: true

  - type: dropdown
    id: Android Version
    attributes:
      label: Which version of Android are you seeing the problem on?
      multiple: true
    placeholder: ex. v10.0
    validations:
      required: true
      

  - type: textarea
    id: logs
    attributes:
      label: Code to produce this issue.
      description: Please copy and paste any relevant code to re-produce this issue. And the version of the browser you are using. 
      render: shell
